# Generated by Django 4.0.4 on 2022-05-26 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AaCargo',
            fields=[
                ('cargo_cargo', models.CharField(max_length=100)),
                ('cargo_quantity', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('cargo_loadingport', models.CharField(blank=True, max_length=100, null=True)),
                ('cargo_dischargingport', models.CharField(blank=True, max_length=100, null=True)),
                ('cargo_loadingrate', models.CharField(blank=True, max_length=100, null=True)),
                ('cargo_dischargingrate', models.CharField(blank=True, max_length=100, null=True)),
                ('cargo_laydate', models.DateField(blank=True, null=True)),
                ('cargo_canceldate', models.DateField(blank=True, null=True)),
                ('cargo_indate', models.DateField(blank=True, null=True)),
                ('cargo_comm', models.FloatField(blank=True, null=True)),
                ('cargo_broker', models.CharField(blank=True, max_length=100, null=True)),
                ('cargo_charterers', models.CharField(blank=True, max_length=100, null=True)),
                ('cargo_seq', models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'aa_cargo',
                'managed': False,
            },
        ),
    ]
