# Generated by Django 4.0.4 on 2022-04-27 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AaShip',
            fields=[
                ('ship_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('deadweight', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('built', models.DateField(blank=True, null=True)),
                ('loa', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('grain', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('beam', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('bale', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('speed', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('consumption', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('eco_speed', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('eco_cons', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('gear', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('ship_date', models.DateField(blank=True, null=True)),
                ('ship_indate', models.DateField(blank=True, null=True)),
                ('ship_broker', models.CharField(blank=True, max_length=50, null=True)),
                ('ship_port', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'aa_ship',
                'managed': False,
            },
        ),
    ]
